# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Ulteam
subtitle: "Libraries"
email: chernyshev@ulteam.ru
name: "Ulteam LLC"
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ulteam.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  ulteam
masthead_title: "Ulteam"

# for search settings
collections:
    pages:
        output: true
        permalink: /pages/:path

search: true # true, false (default)
search_full_content: true # true, false (default)
search_provider          : lunr

lunr_settings:
  collections: 
  - pages

# lunr_search:
#   js_dir: "assets/js/lunr"
#   min_length: 3


encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      comments: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      search: true
      search_full_content: true
      # read_time: true
      sidebar:
        nav: "npm"
      toc: true
      breadcrumbs: true  # disabled by default

minimal_mistakes_skin: "contrast"
teaser: "/assets/images/ulteam_logo.png"
# locale: ru-RU
# timezone: "Europe/Moscow"

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.17.0"
plugins:
  - jekyll-feed
  - jekyll-include-cache

  # Reading Files
include:
  - _pages
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# theme: jekyll-theme-minimal
theme: jekyll-theme-minimal